version: '3.5'
volumes:
  mysql-data:
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius_test
  migrate:
    image: migrate/migrate:v4.11.0
    volumes:
      - ../../services/db/migrations:/migrations
      - ./migrate.sh:/migrate.sh
    restart: "no"
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: ["/migrate.sh"]
